name: nads25_frontend
description: NADS25 Flutter Web
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  go_router: ^17.0.1

flutter:
  uses-material-design: true
